AxControlWeb/Controllers/CARTEL_MULTILEDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Newtonsoft.Json;
using System.Data.Entity.Migrations;

namespace AxControlWeb.Controllers
{
    public class CARTEL_MULTILEDController : Controller
    {
        private AxControlORAEntities db = new AxControlORAEntities();

        /// <summary>
        /// Vista parcial del control, donde se muestra el mensaje acutal del cartel, y un botón que redirige a la configuración
        /// </summary>
        /// <param name="idCartel">El id del cartel es el mismo que el id del sector</param>
        /// <returns></returns>
        public PartialViewResult CartelMultiLED(int idCartel)
        {
            CARTEL_MULTILED oCartel = db.CARTEL_MULTILED.Where(a => a.ID_CARTEL == idCartel).FirstOrDefault();
            ViewBag.oCartel = oCartel;
            return PartialView();
        }

        [HttpGet]
        public ViewResult ConfigCartelMultiLED(int idCartel)
        {
            CARTEL_MULTILED oCartel = db.CARTEL_MULTILED.Where(a => a.ID_CARTEL == idCartel).FirstOrDefault();
            return View(oCartel);
        }

        [HttpPost]
        public ActionResult ConfigCartelMultiLED(CARTEL_MULTILED oCartel)
        {
            db.CARTEL_MULTILED.AddOrUpdate(oCartel);
            db.SaveChanges();
            return RedirectToAction("Control","ControlAcceso",new { idControl = oCartel.ID_CONTROL_ACCESO });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AxControlWeb/Controllers/ComandosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Controles;
namespace AxControlWeb.Controllers
{
    public class ComandosController : Controller
    {
        private AxDriverORAEntities db = new AxDriverORAEntities();


        public void GenerarComando(int idSector, int idComando, string tag)
        {
            var axComando = (from ac in db.DATO_WORDINT where ac.ID_SECTOR == idSector && ac.TAG == tag select ac).FirstOrDefault();
            if (axComando != null)
            {
                axComando.VALOR = idComando;
                axComando.FLAG_RW = true;
                db.SaveChanges();
            }

        }
        public void GenerarComandoDword(int idSector, int idComando, string tag)
        {
            var axComando = (from ac in db.DATO_DWORDDINT where ac.ID_SECTOR == idSector && ac.TAG == tag select ac).FirstOrDefault();
            if (axComando != null)
            {
                axComando.VALOR = idComando;
                axComando.FLAG_RW = true;
                db.SaveChanges();
            }

        }

        public void GenerarComandoCartel(int idComando, int idSector, string mensaje)
        {
            try
            {
                AxControlORAEntities dbControl = new AxControlORAEntities();
                var control = (from c in dbControl.SECTOR where c.ID_SECTOR == idSector select c).FirstOrDefault();
                int ID_CONTROL = (int)control.ID_CONTROL_ACCESO;

                COMANDO newComando = new COMANDO();
                newComando.ID_CONTROL = ID_CONTROL;
                newComando.ID_SECTOR = idSector;
                newComando.PROCESADO = 0;
                newComando.TAG = idComando.ToString();
                newComando.MENSAJE = mensaje;
                newComando.ID_TIPO_COMANDO = (int)Constante.TIPO_COMANDO.ESCRIBIR_CARTEL;
                dbControl.COMANDO.Add(newComando);
                dbControl.SaveChanges();

                dbControl.Dispose();
                dbControl = null;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public void TagLeidoManual(int idSector, string tag)
        {

            try
            {
                AxControlORAEntities dbControl = new AxControlORAEntities();
                var control = (from c in dbControl.SECTOR where c.ID_SECTOR == idSector select c).FirstOrDefault();
                int ID_CONTROL = (int)control.ID_CONTROL_ACCESO;

                COMANDO newComando = new COMANDO();
                newComando.ID_CONTROL = ID_CONTROL;
                newComando.ID_SECTOR = idSector;
                newComando.PROCESADO = 0;
                newComando.TAG = tag;
                dbControl.COMANDO.Add(newComando);
                dbControl.SaveChanges();

                dbControl.Dispose();
                dbControl = null;
            }
            catch (Exception ex)
            {

            }

        }

        public void ComandoControl(int idSector, string tag, int idTipoComando)
        {

            try
            {
                AxControlORAEntities dbControl = new AxControlORAEntities();
                var control = (from c in dbControl.SECTOR where c.ID_SECTOR == idSector select c).FirstOrDefault();
                int ID_CONTROL = (int)control.ID_CONTROL_ACCESO;

                COMANDO newComando = new COMANDO();
                newComando.ID_CONTROL = ID_CONTROL;
                newComando.ID_SECTOR = idSector;
                newComando.PROCESADO = 0;
                newComando.TAG = tag;
                newComando.ID_TIPO_COMANDO = idTipoComando;
                dbControl.COMANDO.Add(newComando);
                dbControl.SaveChanges();

                dbControl.Dispose();
                dbControl = null;
            }
            catch (Exception ex)
            {

            }

        }

        // GET: Comandos
        public ActionResult Index()
        {
            var dATO_WORDINT = db.DATO_WORDINT.Include(d => d.PLC);
            return View(dATO_WORDINT.ToList());
        }

        // GET: Comandos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATO_WORDINT dATO_WORDINT = db.DATO_WORDINT.Find(id);
            if (dATO_WORDINT == null)
            {
                return HttpNotFound();
            }
            return View(dATO_WORDINT);
        }

        // GET: Comandos/Create
        public ActionResult Create()
        {
            ViewBag.FK_PLC = new SelectList(db.PLC, "ID", "NOMBRE");
            return View();
        }

        // POST: Comandos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TAG,NUM_WORD,VALOR,QC,FLAG_RW,FK_PLC,RW,ID_SECTOR,NUM_DB")] DATO_WORDINT dATO_WORDINT)
        {
            if (ModelState.IsValid)
            {
                db.DATO_WORDINT.Add(dATO_WORDINT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_PLC = new SelectList(db.PLC, "ID", "NOMBRE", dATO_WORDINT.FK_PLC);
            return View(dATO_WORDINT);
        }

        // GET: Comandos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATO_WORDINT dATO_WORDINT = db.DATO_WORDINT.Find(id);
            if (dATO_WORDINT == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_PLC = new SelectList(db.PLC, "ID", "NOMBRE", dATO_WORDINT.FK_PLC);
            return View(dATO_WORDINT);
        }

        // POST: Comandos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TAG,NUM_WORD,VALOR,QC,FLAG_RW,FK_PLC,RW,ID_SECTOR,NUM_DB")] DATO_WORDINT dATO_WORDINT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dATO_WORDINT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_PLC = new SelectList(db.PLC, "ID", "NOMBRE", dATO_WORDINT.FK_PLC);
            return View(dATO_WORDINT);
        }

        // GET: Comandos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATO_WORDINT dATO_WORDINT = db.DATO_WORDINT.Find(id);
            if (dATO_WORDINT == null)
            {
                return HttpNotFound();
            }
            return View(dATO_WORDINT);
        }

        // POST: Comandos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DATO_WORDINT dATO_WORDINT = db.DATO_WORDINT.Find(id);
            db.DATO_WORDINT.Remove(dATO_WORDINT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AxControlWeb/Views/CARTEL_MULTILED/CartelMultiLED.cshtml
@{
    Entidades.CARTEL_MULTILED oCartel = ViewBag.oCartel;
}

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-6 text-left">
                                Cartel MultiLED
                            </div>
                            <div class="text-right col-6">
                                <button class="btn btn-primary" id="@(oCartel.ID_CARTEL.ToString() + "btnConfig")" onclick="location.href='@Url.Action("ConfigCartelMultiLED", "CARTEL_MULTILED", new { idCartel = oCartel.ID_CARTEL })';return false;">
                                    <i class="fa fa-fw fa-gear"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <div class="text-center">
                            <div id="mensajeCartel">
                                @{
                                    switch (oCartel.PASO_ACTUAL)
                                    {
                                        case (int)Entidades.Constante.PasosCartelMultiled.SistemaDetenido:
                                            <b>
                                                SISTEMA DETENIDO
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoFijoPorDefecto:
                                            <b>
                                                ACA TIMBUES
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoFijoAVANCE:
                                            <b>
                                                AVANCE
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoFijoRETROCEDA:
                                            <b>
                                                RETROCEDA
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoFijoESPERE:
                                            <b>
                                                ESPERE
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoVariable:
                                            <b>
                                                @oCartel.MENSAJE_ACTUAL
                                            </b>
                                            break;
                                        case (int)Entidades.Constante.PasosCartelMultiled.TextoFijoFUERADESERVICIO:
                                            <b>
                                                FUERA DE SERVICIO
                                            </b>
                                            break;
                                    }
                                }
                            </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

AxControlWeb/Views/CARTEL_MULTILED/ConfigCartelMultiLED.cshtml
@model Entidades.CARTEL_MULTILED
@{
    ViewBag.Title = "ConfigCartelMultiLED";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="~/Scripts/Comandos.js"></script>
<div class="border rounded text-center" style="padding:5px;background-color:whitesmoke">
    <h2>Cartel MultiLED @Model.DESCRIPCION</h2>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <button type="button" class="btn btn-outline-dark btn-lg" onclick="GenerarComandoCartel('1','@Model.ID_CARTEL',' ');">ACA TIMBUES</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-outline-success btn-lg" onclick="GenerarComandoCartel('2','@Model.ID_CARTEL',' ');">AVANCE</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-outline-danger btn-lg" onclick="GenerarComandoCartel('3','@Model.ID_CARTEL',' ');">RETROCEDA</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-outline-warning btn-lg" onclick="GenerarComandoCartel('4','@Model.ID_CARTEL',' ');">ESPERE</button>
            </div>
            <div class="col-sm">
                <button type="button" class="btn btn-danger btn-lg" onclick="GenerarComandoCartel('7','@Model.ID_CARTEL',' ');">PARE</button>
            </div>
        </div>
    </div>
    <hr />
    <form>
        <div class="row" style="align-items:center">
            <div class="col" style="text-align:right">
                <label class="col-form-label-lg">Texto personalizado: </label>
            </div>
            <div class="col">
                <input type="text" class="form-control" id="textoMensajeCartel">
            </div>
            <div class="col" style="text-align:left">
                <button type="button" class="btn btn-primary btn-lg" onclick="GenerarComandoCartel('5','@Model.ID_CARTEL',document.getElementById('textoMensajeCartel').value);">Escribir</button>
            </div>
        </div>
    </form>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.ID_CARTEL)
        @Html.HiddenFor(model => model.DESCRIPCION)
        @Html.HiddenFor(model => model.ID_CONTROL_ACCESO)
        @Html.HiddenFor(model => model.TAG)
        <div class="">
            <div id="Config" class="text-center">
                <label class="col-form-label-lg">IP: </label>
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "mx-auto input-sm text-center form-control w-25", @style = "text-align:center;padding:0px;" } })
                <label class="col-form-label-lg">Puerto: </label>
                @Html.EditorFor(model => model.PORT, new { htmlAttributes = new { @class = "mx-auto input-sm text-center form-control w-25", @style = "text-align:center;padding:0px;", @type = "number" } })
                <label class="col-form-label-lg">Mensaje por defecto: </label>
                @Html.EditorFor(model => model.MSJ_POR_DEFECTO, new { htmlAttributes = new { @class = "mx-auto input-sm text-center form-control w-25", @style = "text-align:center;padding:0px;" } })
                <br />
                <button class="btn btn-lg btn-dark text-center" id="btnCambioTiempoRetardoSENSOR" type="submit" onclick="window.history.go(-1);">Guardar Config.</button>
            </div>
        </div>
    }
</div>


<script>
    window.onload = function sum() {
        document.getElementById("accordionSidebar").className = "navbar-nav bg-aumax sidebar sidebar-dark accordion toggled";
    };

    function GenerarComandoCartel(idComando, idSector, mensaje) {
        var url = "@Html.Raw(Url.Action("GenerarComandoCartel", "Comandos", new { idComando="-1", idSector ="-2", mensaje="-3"}))";
        url = url.replace("-1", idComando);
        url = url.replace("-2", idSector);
        url = url.replace("-3", mensaje);
        $.get(url, function (data) { });
    };
</script>