AxControlWeb/Controllers/ControlAccesoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Newtonsoft.Json;

namespace AxControlWeb.Controllers
{
    [Authorize]
    public class ControlAccesoController : Controller
    {
        private AxControlORAEntities db = new AxControlORAEntities();

        public string GetControlesAcceso()
        {
            List<CONTROL_ACCESO> ListaControlAcceso = db.CONTROL_ACCESO.OrderBy(a => a.ID_CONTROL_ACCESO).ToList();
            return JsonConvert.SerializeObject(ListaControlAcceso, Formatting.Indented,
               new JsonSerializerSettings
               {
                   ReferenceLoopHandling = ReferenceLoopHandling.Ignore
               });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);    
        }


        public ActionResult Control(int idControl)
        {
            var controlActual = (from ca in db.CONTROL_ACCESO where ca.ID_CONTROL_ACCESO == idControl select ca).FirstOrDefault();
            return View(controlActual);
        }



        public ActionResult Control_(int idControl)
        {
            var controlActual = (from ca in db.CONTROL_ACCESO where ca.ID_CONTROL_ACCESO == idControl select ca).FirstOrDefault();
            return PartialView(controlActual);
        }

        public ActionResult Semaforo(int idSector)
        {
            AxDriverORAEntities dbX = new AxDriverORAEntities();
            var Semaforo1 = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("SEMAFORO1") select s).FirstOrDefault();
            var Semaforo2 = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("SEMAFORO2") select s).FirstOrDefault();

            if (Semaforo1 == null && Semaforo2 == null)
            {
                var Semaforo = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("SEMAFORO") && s.TAG.Contains("Estado") select s).FirstOrDefault();
                ViewBag.estadoSemaforo = Semaforo.VALOR.ToString();
                return View(Semaforo);
            }

            if (Semaforo1 != null)
            {
                ViewBag.estadoSemaforo1 = Semaforo1.VALOR.ToString();
            }
            else
            {
                ViewBag.estadoSemaforo1 = "NULL";
            }

            if (Semaforo2 != null)
            {
                ViewBag.estadoSemaforo2 = Semaforo2.VALOR.ToString();
                return View(Semaforo2);
            }
            else
            {
                ViewBag.estadoSemaforo2 = "NULL";
                return View(Semaforo1);
            }

        }

        public ActionResult Barrera(int idSector)
        {
            AxDriverORAEntities dbX = new AxDriverORAEntities();
            var Barrera1 = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("BARRERA") select s).FirstOrDefault();
            var SensorBarrera1 = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("S_BARRERA.TiempoRet") select s).FirstOrDefault();

            if (Barrera1 != null)
            {
                ViewBag.Barrera1 = Barrera1.VALOR.ToString();
            }
            else
            {
                ViewBag.Barrera1 = "NULL";
            }
            ViewBag.Sensor = SensorBarrera1.VALOR;
            return View(Barrera1);
        }

        public ActionResult Sensor(int idSector)
        {
            AxDriverORAEntities dbX = new AxDriverORAEntities();
            var Sensor1 = (from s in dbX.DATO_WORDINT where s.ID_SECTOR == idSector && s.TAG.Contains("S_LECTURA") select s).FirstOrDefault();
            if (Sensor1 != null)
            {
                ViewBag.estadoSensor1 = Sensor1.VALOR.ToString();
            }
            else
            {
                ViewBag.estadoSensor1 = "NULL";
            }
            return View(Sensor1);
        }

        public ActionResult ComandosSensor(int idSector, string tag)
        {
            AxDriverORAEntities dbD = new AxDriverORAEntities();
            Entidades.Sensor oSensor = new Entidades.Sensor();
            oSensor.Descripcion = tag;
            oSensor.Estado = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".Estado")).FirstOrDefault();
            oSensor.Habilitacion = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".Habilitacion")).FirstOrDefault();
            oSensor.TiempoRet = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".TiempoRet")).FirstOrDefault();
            ViewBag.oSensor = oSensor;
            SECTOR oSector = db.SECTOR.Where(a => a.ID_SECTOR == idSector).FirstOrDefault();
            ViewBag.oSector = oSector;
            return View();
        }

        public ActionResult ComandosBarrera(int idSector, string tag)
        {
            AxDriverORAEntities dbD = new AxDriverORAEntities();
            Entidades.Barrera oBarrera = new Entidades.Barrera();
            oBarrera.Descripcion = tag;
            oBarrera.Estado = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".Estado")).FirstOrDefault();
            oBarrera.Comando = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".Comando")).FirstOrDefault();
            oBarrera.HabSenPosicion = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG.Contains(tag + ".HabSenPosicion")).FirstOrDefault();
            ViewBag.oBarrera = oBarrera;
            SECTOR oSector = db.SECTOR.Where(a => a.ID_SECTOR == idSector).FirstOrDefault();
            ViewBag.oSector = oSector;
            return View();
        }

        /// <summary>
        /// Devuelvo como JSON el estado que tiene el dispositivo
        /// </summary>
        /// <param name="idSector"></param>
        /// <param name="tag"></param>
        /// <returns></returns>
        public string GetJsonEstadoDispositivo(int idSector, string tag)
        {
            AxDriverORAEntities dbD = new AxDriverORAEntities();
            int? inEstadoDispositivo = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == tag).Select(a => a.VALOR).FirstOrDefault();
            return JsonConvert.SerializeObject(Convert.ToInt16(inEstadoDispositivo), Formatting.Indented,
              new JsonSerializerSettings
              {
                  ReferenceLoopHandling = ReferenceLoopHandling.Ignore
              });            
        }

        public ActionResult ComandosSemaforo(int idSector, string tag)
        {
            AxDriverORAEntities dbD = new AxDriverORAEntities();
            DATO_WORDINT oSemaforoEstado = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG==(tag+".Estado")).FirstOrDefault();
            DATO_WORDINT oSemaforoComando = dbD.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == (tag + ".Comando")).FirstOrDefault();
            ViewBag.oSemaforoEstado = oSemaforoEstado;
            ViewBag.oSemaforoComando = oSemaforoComando;
            SECTOR oSector = db.SECTOR.Where(a => a.ID_SECTOR == idSector).FirstOrDefault();
            ViewBag.oSector = oSector;
            ViewBag.Tag = tag;
            return View();
        }

        public ActionResult Ayuda(int idSector)
        {
            return View();
        }

        public PartialViewResult DinamismoPorteria_(int idSector)
        {
            AxDriverORAEntities dbD = new AxDriverORAEntities();
            SECTOR oSector = db.SECTOR.Where(a => a.ID_CONTROL_ACCESO == idSector).FirstOrDefault();

            if (oSector == null)
            {
                oSector = db.SECTOR.Where(a => a.ID_SECTOR == idSector).FirstOrDefault();
            }

            SECTOR_PORTERIA newSectPorteria = new SECTOR_PORTERIA();
            newSectPorteria.NOMBRE = oSector.NOMBRE;
            newSectPorteria.ID_SECTOR = oSector.ID_SECTOR;
            newSectPorteria.ID_CONTROL_ACCESO = oSector.ID_CONTROL_ACCESO;
            newSectPorteria.DESCRIPCION = oSector.DESCRIPCION;

            var Barrera = (from o in dbD.DATO_WORDINT where o.ID_SECTOR == oSector.ID_SECTOR && o.TAG == "BARRERA.Estado" select o).FirstOrDefault();
            if (Barrera != null)
            {
                newSectPorteria.Barrera = (int)Barrera.VALOR;
            }
            else
            {
                newSectPorteria.Barrera = 0;
            }

            var Sensor = (from o in dbD.DATO_WORDINT where o.ID_SECTOR == oSector.ID_SECTOR && o.TAG == "S_BARRERA.Estado" select o).FirstOrDefault();
            if (Sensor != null)
            {
                newSectPorteria.Sensor = (int)Sensor.VALOR;
            }
            else
            {
                newSectPorteria.Sensor = 0;
            }

            var EstadoSem1 = (from a in dbD.DATO_WORDINT where a.ID_SECTOR == oSector.ID_SECTOR && a.TAG == "SEMAFORO1.Estado" select a).FirstOrDefault();
            if (EstadoSem1 != null)
            {
                newSectPorteria.Semaforo1 = (int)EstadoSem1.VALOR;
            }
            else
            {
                newSectPorteria.Semaforo1 = 0;
            }
            var EstadoSem2 = (from a in dbD.DATO_WORDINT where a.ID_SECTOR == oSector.ID_SECTOR && a.TAG == "SEMAFORO2.Estado" select a).FirstOrDefault();
            if (EstadoSem2 != null)
            {
                newSectPorteria.Semaforo2 = (int)EstadoSem2.VALOR;
            }
            else
            {
                newSectPorteria.Semaforo2 = 0;
            }
            var Espira = (from o in dbD.DATO_WORDINT where o.ID_SECTOR == oSector.ID_SECTOR && o.TAG == "S_LECTURA.Estado" select o).FirstOrDefault();
            if (Espira != null)
            {
                newSectPorteria.Espira = (int)Espira.VALOR;
            }

AxControlWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
namespace AxControlWeb.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
         
                return View();
            

            
        }

        public PartialViewResult mapa()
        {
            try
            {
                AxControlORAEntities db = new AxControlORAEntities();


                var listaAlertas = (from N in db.NOTIFICACION where N.TIPO_NOTIFICACION == "1" select N).ToList();
                db.Dispose();
                db = null;
                ViewBag.T1 = "";
                ViewBag.T2 = "";
                ViewBag.T3 = "";
                ViewBag.T4 = "";
                ViewBag.T5 = "";
                ViewBag.T6 = "";
                ViewBag.T7 = "";
                ViewBag.T8 = "";
                ViewBag.T9 = "";
                ViewBag.T12 = "";

                foreach (var item in listaAlertas)
                {
                    switch ((int)item.ID_CONTROL_ACCESO)
                    {
                        case 100:
                            ViewBag.T1 = "ALERTA";
                            break;
                        case 200:
                            ViewBag.T2 = "ALERTA";
                            break;
                        case 300:
                            ViewBag.T3 = "ALERTA";
                            break;
                        case 400:
                            ViewBag.T4 = "ALERTA";
                            break;
                        case 500:
                            ViewBag.T5 = "ALERTA";
                            break;
                        case 600:
                            ViewBag.T6 = "ALERTA";
                            break;
                        case 700:
                            ViewBag.T7 = "ALERTA";
                            break;
                        case 800:
                            ViewBag.T8 = "ALERTA";
                            break;
                        case 900:
                            ViewBag.T9 = "ALERTA";
                            break;
                        case 1200:
                            ViewBag.T12 = "ALERTA";
                            break;
                    }


                }

                return PartialView();
            }
            catch (Exception ex)
            {

                return PartialView();
            }

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AxControlWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AxControlWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AxControlWeb/Views/Home/Index.cshtml
@*@model Entidades.CONTROL_ACCESO*@
@{
    ViewBag.Title = "Principal";
}

<div id="mapaDinamico" >
    @Html.Action("mapa", "Home")
</div>


<script type="text/javascript">
    window.onload = function sum() {
        setInterval(function () {
            $.get("/Home/mapa").done(function (data){

                    $("#mapaDinamico").html(data);
               
            });
            return false;
        }, 5000);

    };
</script>

AxControlWeb/Views/Home/mapa.cshtml
<div class="jumbotron">
    <table class="table-responsive">
        <tr>
            <td><img src="~/Content/img/mapa/44.png" /></td>
            <td><img src="~/Content/img/mapa/43.png" /></td>
            @if (ViewBag.T1 == "ALERTA")
            {
                <td style="background-color:red" ><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =100 })'" src="~/Content/img/mapa/42.png" title="T1" name="T100"  /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/42.png" title="T1" /></td>
            }
            <td><img src="~/Content/img/mapa/41.png" /></td>
            <td><img src="~/Content/img/mapa/40.png" /></td>
            <td><img src="~/Content/img/mapa/39.png" /></td>
            <td><img src="~/Content/img/mapa/38.png" /></td>
            <td><img src="~/Content/img/mapa/37.png" /></td>
            <td><img src="~/Content/img/mapa/36.png" /></td>
            <td><img src="~/Content/img/mapa/35.png" /></td>
            <td><img src="~/Content/img/mapa/34.png" /></td>
        </tr>
        <tr>

            <td><img src="~/Content/img/mapa/33.png" /></td>
            <td><img src="~/Content/img/mapa/32.png" /></td>
            <td><img src="~/Content/img/mapa/31.png" /></td>
            @if (ViewBag.T2 == "ALERTA")
            {
                <td style="background-color:red" onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =200 })'"><img src="~/Content/img/mapa/30.png" name="T200" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/30.png" title="T2" /></td>
            }
            <td><img src="~/Content/img/mapa/29.png" /></td>
            <td><img src="~/Content/img/mapa/28.png" /></td>
            <td><img src="~/Content/img/mapa/27.png" /></td>
            <td><img src="~/Content/img/mapa/26.png" /></td>
            <td><img src="~/Content/img/mapa/25.png" /></td>
            <td><img src="~/Content/img/mapa/24.png" /></td>
            <td><img src="~/Content/img/mapa/23.png" /></td>
        </tr>
        <tr>

            <td><img src="~/Content/img/mapa/22.png" /></td>
            <td><img src="~/Content/img/mapa/21.png" /></td>
            <td><img src="~/Content/img/mapa/20.png" /></td>
            <td><img src="~/Content/img/mapa/19.png" /></td>
            <td><img src="~/Content/img/mapa/18.png" /></td>
            <td><img src="~/Content/img/mapa/17.png" /></td>
            <td><img src="~/Content/img/mapa/16.png" /></td>
            @if (ViewBag.T7 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =700 })'"  src="~/Content/img/mapa/15.png" name="T700" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/15.png" title="T7" /></td>
            }
            <td><img src="~/Content/img/mapa/14.png" /></td>
            @if (ViewBag.T12 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =1200 })'"  src="~/Content/img/mapa/13.png" title="T12" name="T1200" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/13.png" title="T12" /></td>
            }
            <td><img src="~/Content/img/mapa/12.png" /></td>
        </tr>
        <tr>

            <td><img src="~/Content/img/mapa/11.png" /></td>
            <td><img src="~/Content/img/mapa/10.png" /></td>
            <td><img src="~/Content/img/mapa/9.png" /></td>
            <td><img src="~/Content/img/mapa/8.png" /></td>
            <td><img src="~/Content/img/mapa/7.png" /></td>
            @if (ViewBag.T4 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =400 })'"  src="~/Content/img/mapa/6.png" title="T4" name="T400" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/6.png" title="T4" /></td>
            }

            <td><img src="~/Content/img/mapa/5.png" /></td>
            <td><img src="~/Content/img/mapa/4.png" /></td>
            <td><img src="~/Content/img/mapa/3.png" /></td>
            <td><img src="~/Content/img/mapa/2.png" /></td>
            <td><img src="~/Content/img/mapa/1.png" /></td>
        </tr>
        <tr>

            <td><img src="~/Content/img/mapa/45.png" /></td>
            @if (ViewBag.T3 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =300 })'"  src="~/Content/img/mapa/46.png" title="T3" name="T300" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/46.png" title="T3" /></td>
            }
            <td><img src="~/Content/img/mapa/47.png" /></td>
            <td><img src="~/Content/img/mapa/48.png" /></td>
            <td><img src="~/Content/img/mapa/49.png" /></td>
            <td><img src="~/Content/img/mapa/50.png" /></td>
            <td><img src="~/Content/img/mapa/51.png" /></td>
            @if (ViewBag.T5 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =500 })'"  src="~/Content/img/mapa/52.png" title="T5" name="T500" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/52.png" title="T5" /></td>
            }

            @if (ViewBag.T6 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =600 })'"  src="~/Content/img/mapa/53.png" title="T6" name="T600" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/53.png" title="T6" /></td>
            }

            @if (ViewBag.T8 == "ALERTA")
            {
                <td style="background-color:red"><img  onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =800 })'"  src="~/Content/img/mapa/54.png" title="T8" name="T800" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/54.png" /></td>
            }


            @if (ViewBag.T9 == "ALERTA")
            {
                <td style="background-color:red"><img onclick="location.href='@Url.Action("Control", "ControlAcceso", new { idControl =900 })'"  src="~/Content/img/mapa/55.png" title="T9" name="T900" /></td>
            }
            else
            {
                <td><img src="~/Content/img/mapa/55.png" title="T10" /></td>
            }
        </tr>
    </table>
</div>
<script type="text/javascript">

    function parpadeo() {

            for (var i = 100; i < 1300; i= i +100) {
                var imagenDinamismo = document.images["T" + i.toString()];
                if (imagenDinamismo != null) { imagenDinamismo.style.opacity = (imagenDinamismo.style.opacity == "1") ? "0.5" : "1"; }
            }
   
        }
        setInterval("parpadeo()", 1000);
     
</script>