AxControlWeb/Controllers/SectoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entidades;
using axControl.Models;

namespace AxControlWeb.Controllers
{
    public class SectoresController : Controller
    {
        private AxControlORAEntities db = new AxControlORAEntities();
        private AxDriverORAEntities dbDriv = new AxDriverORAEntities();

        
        public PartialViewResult _sector(int idSector)
        {
            var sectorActual = (from sa in db.SECTOR where sa.ID_SECTOR == idSector select sa).FirstOrDefault();
           
            return PartialView(sectorActual);
        }

        public PartialViewResult _DinamismoPorteria(int idSector)
        {
            var Barrera = (from o in dbDriv.DATO_WORDINT where o.ID_SECTOR == idSector && o.TAG == "BARRERA.Estado" select o).FirstOrDefault();
            var Sensor = (from o in dbDriv.DATO_WORDINT where o.ID_SECTOR == idSector && o.TAG == "S_BARRERA.Estado" select o).FirstOrDefault();
            var Semaforo1 = (from o in dbDriv.DATO_WORDINT where o.ID_SECTOR == idSector && o.TAG == "SEMAFORO1.Estado" select o).FirstOrDefault();
            var Semaforo2 = (from o in dbDriv.DATO_WORDINT where o.ID_SECTOR == idSector && o.TAG == "SEMAFORO2.Estado" select o).FirstOrDefault();
            var Espira = (from o in dbDriv.DATO_WORDINT where o.ID_SECTOR == idSector && o.TAG == "S_LECTURA.Estado" select o).FirstOrDefault();



            if (Barrera!=null)
            {
                switch (Barrera.VALOR)
                {
                    case (int)Constante.EstadoBarrera.ArribaAutomatica:
                    case (int)Constante.EstadoBarrera.ArribaManual:
                        ViewBag.estadoBarrera = "barrera levantada";
                        break;
                    case (int)Constante.EstadoBarrera.AbajoAutomatica:
                    case (int)Constante.EstadoBarrera.AbajoManual:
                    case (int)Constante.EstadoBarrera.Falla:
                        ViewBag.estadoBarrera = "barrera baja_";
                        break;
                }
            }
            else
            {
                ViewBag.estadoBarrera = "NULL";
            }

            if(Sensor!=null)
            {
                switch (Sensor.VALOR)
                {
                    case (int)Constante.EstadoSensor.SensorConPresencia:
                        ViewBag.estadoSensor = "Sensor_Encendido";
                        break;
                    case (int)Constante.EstadoSensor.SensorSinPresencia:
                    case (int)Constante.EstadoSensor.Falla:
                    case (int)Constante.EstadoSensor.Deshabilitado:
                        ViewBag.estadoSensor = "Sensor_Apagado";
                        break;

                }
            }
            else
            {
                ViewBag.estadoSensor = "NULL";
            }

            if (Semaforo1!=null)
            {
                switch (Semaforo1.VALOR)
                {
                    case (int)Constante.EstadoSemaforo.Verde:
                        ViewBag.estadoSemaforo1 = "VERDE";
                        break;
                    case (int)Constante.EstadoSemaforo.Rojo:
                        ViewBag.estadoSemaforo1 = "ROJO";
                        break;
                    case (int)Constante.EstadoSemaforo.Apagado:
                        ViewBag.estadoSemaforo1 = "APAGADO";
                        break;
                }
            }
            else
            {
                ViewBag.estadoSemaforo1 = "NULL";
            }

            if (Semaforo2 != null)
            {
                switch (Semaforo2.VALOR)
                {
                    case (int)Constante.EstadoSemaforo.Verde:
                        ViewBag.estadoSemaforo2 = "VERDE";
                        break;
                    case (int)Constante.EstadoSemaforo.Rojo:
                        ViewBag.estadoSemaforo2 = "ROJO";
                        break;
                    case (int)Constante.EstadoSemaforo.Apagado:
                        ViewBag.estadoSemaforo2 = "APAGADO";
                        break;
                }
            }
            else
            {
                ViewBag.estadoSemaforo2 = "NULL";
            }

            if (Espira != null)
            {
                switch (Espira.VALOR)
                {
                    case (int)Constante.EstadoSensor.SensorConPresencia:
                        ViewBag.estadoEspira = "Espira_Con_Lectura";
                        break;
                    case (int)Constante.EstadoSensor.SensorSinPresencia:
                    case (int)Constante.EstadoSensor.Falla:
                    case (int)Constante.EstadoSensor.Deshabilitado:
                        ViewBag.estadoEspira = "Espira_Sin_Lectura";
                        break;
                }
            }
            else
            {
                ViewBag.estadoEspira = "NULL";
            }
            var sectorActual = (from sa in db.SECTOR where sa.ID_SECTOR == idSector select sa).FirstOrDefault();
            return PartialView(sectorActual);
        }

        #region "Balanza"

        public PartialViewResult _DinamismoBalanza(int idSector)
        {
            SECTOR oSector = db.SECTOR.Where(a => a.ID_SECTOR == idSector).FirstOrDefault();
            int? EstadoBar1 = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "BARRERA1.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoBar2 = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "BARRERA2.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoS1_Bar = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "S1_BARRERA.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoS2_Bar = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "S2_BARRERA.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoS1_Pos = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "S1_POSICION.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoS2_Pos = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "S2_POSICION.Estado").Select(a => a.VALOR).FirstOrDefault();
            int? EstadoS_Lect = dbDriv.DATO_WORDINT.Where(a => a.ID_SECTOR == idSector && a.TAG == "S_LECTURA.Estado").Select(a => a.VALOR).FirstOrDefault();

            ViewBag.oSector = oSector;
            ViewBag.EstadoBar1 = EstadoBar1 == (int)Constante.EstadoBarrera.ArribaAutomatica || EstadoBar1 == (int)Constante.EstadoBarrera.ArribaAutomatica ? "barrera levantada" : "barrera baja_";
            ViewBag.EstadoBar2 = EstadoBar2 == (int)Constante.EstadoBarrera.ArribaAutomatica || EstadoBar2 == (int)Constante.EstadoBarrera.ArribaAutomatica ? "barrera levantada" : "barrera baja_";
            ViewBag.EstadoS1_Bar = EstadoS1_Bar == (int)Constante.EstadoSensor.SensorConPresencia ? "Sensor_Encendido" : "Sensor_Apagado";
            ViewBag.EstadoS2_Bar = EstadoS2_Bar == (int)Constante.EstadoSensor.SensorConPresencia ? "Sensor_Encendido" : "Sensor_Apagado";
            ViewBag.EstadoS1_Pos = EstadoS1_Pos == (int)Constante.EstadoSensor.SensorConPresencia ? "Sensor_Encendido" : "Sensor_Apagado";
            ViewBag.EstadoS2_Pos = EstadoS2_Pos == (int)Constante.EstadoSensor.SensorConPresencia ? "Sensor_Encendido" : "Sensor_Apagado";
            ViewBag.EstadoS_Lect = EstadoS_Lect == (int)Constante.EstadoSensor.SensorConPresencia ? "Espira_Con_Lectura" : "Espira_Sin_Lectura";

            return PartialView(oSector);
        }

        public PartialViewResult Balanza(int idSector)
        {

            return PartialView();
        }

        public objBalanza GetBalanza(string tag, int idSector)
        {
            List<DATO_WORDINT> ListDatoWordInt = dbDriv.DATO_WORDINT.Where(a => a.TAG.StartsWith(tag) && a.ID_SECTOR == idSector).ToList();
            List<DATO_BOOL> ListDatoBool = dbDriv.DATO_BOOL.Where(a => a.TAG.StartsWith(tag) && a.ID_SECTOR == idSector).ToList();
            List<DATO_DWORDDINT> ListDatoDWordInt = dbDriv.DATO_DWORDDINT.Where(a => a.TAG.StartsWith(tag) && a.ID_SECTOR == idSector).ToList();
            objBalanza oBalanza = new objBalanza();
            oBalanza.Descripcion = tag;
            oBalanza.LecturaRFID = dbDriv.DATO_WORDINT.Where(a => a.TAG == "BALANZA.LecturaRFID" && a.ID_SECTOR == idSector).SingleOrDefault();
            foreach (DATO_WORDINT item in ListDatoWordInt)
            {
                if (item.TAG.EndsWith("Comando"))
                {
                    oBalanza.Comando = item;
                }
                if (item.TAG.EndsWith("DiferenciaEstabilidad"))
                {
                    oBalanza.DiferenciaEstabilidad = item;
                }
                if (item.TAG.EndsWith("Estado"))
                {
                    oBalanza.Estado = item;
                }
                if (item.TAG.EndsWith("EstadoOld"))
                {
                    oBalanza.EstadoOld = item;
                }
                if (item.TAG.EndsWith("PesoMax"))
                {
                    oBalanza.PesoMax = item;
                }
                if (item.TAG.EndsWith("TiempoEstabilidad"))
                {
                    oBalanza.TiempoEstabilidad = item;
                }
            }
            foreach (DATO_BOOL item in ListDatoBool)
            {
                if (item.TAG.EndsWith("ErrorBal"))
                {
                    oBalanza.dbErrorBal = item;
                }
                if (item.TAG.EndsWith("FueraEquilibrio"))
                {
                    oBalanza.dbFueraEquilibrio = item;
                }
                if (item.TAG.EndsWith("FueraRango"))
                {
                    oBalanza.dbFueraRango = item;
                }

AxControlWeb/Views/Sectores/Botones_.cshtml
@model Entidades.SECTOR

@if (ViewBag.estadoSemaforo2 != "NULL" || ViewBag.estadoSemaforo1 != "NULL")
{
    <div class="column">

        <div class="modal" id="ModalSEMAFOROS" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header" id="DescripcionSemaforos">
                        <b>
                            SEMAFOROS
                        </b>
                    </div>
                    <div class="modal-body text-center">
                        <div id="EstadoSEMAFOROS">
                            @*@Html.Action("Sensor", "ControlesAcceso", new { tag = "S1_BARRERA", idSector = 10 })*@
                        </div>
                        Sector: @Model.ID_SECTOR
                        -
                        PLC: 1
                        @if (ViewBag.estadoSemaforo1 != "NULL")
                        {
                            <hr />
                            <div id="Habilitacion">
                                <b>
                                    <label class="label">Comandos Semaforo 1 </label>
                                </b>
                                <div id="botonesHabilitacion">
                                    <button type="button" class="btn btn-success" id="btnHabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',1,'SEMAFORO1.Comando')">
                                        Verde
                                    </button>
                                    <button type="button" class="btn btn-danger" id="btnDeshabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',2,'SEMAFORO1.Comando')">
                                        Rojo
                                    </button>
                                    <button type="button" class="btn btn-dark" id="btnHabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',1,'SEMAFORO1.Comando')">
                                        Apagado
                                    </button>

                                </div>
                            </div>
                            <hr />
                        }
                        @if (ViewBag.estadoSemaforo2 != "NULL")
                        {
                            <hr />

                            <div id="Habilitacion">
                                <b>
                                    <label class="label">Comandos Semaforo 2 </label>
                                </b>
                                <div id="botonesHabilitacion">
                                    <button type="button" class="btn btn-success" id="btnHabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',1,'SEMAFORO2.Comando')">
                                        Verde
                                    </button>
                                    <button type="button" class="btn btn-danger" id="btnDeshabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',2,'SEMAFORO2.Comando')">
                                        Rojo
                                    </button>
                                    <button type="button" class="btn btn-dark" id="btnHabilitar" onclick="EjecutarComando('@Model.ID_SECTOR',1,'SEMAFORO2.Comando')">
                                        Apagado
                                    </button>

                                </div>
                            </div>
                            <hr />
                        }
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cerrarModal()">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-primary" id="btnSEMAFOROS" data-toggle="modal" data-target="#ModalSEMAFOROS">
            SEMAFOROS
        </button>
    </div>

}

@if (ViewBag.estadoSensor != "NULL")
{
    <div class="column">
        <div class="modal" id="ModalSENSOR" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header" id="DescripcionSensor">
                        <b>
                            SENSOR
                        </b>
                    </div>
                    <div class="modal-body text-center">
                        <div id="EstadoSENSOR">
                            @*@Html.Action("Sensor", "ControlesAcceso", new { tag = "S1_BARRERA", idSector = 10 })*@
                        </div>
                        Sector: @Model.ID_SECTOR
                        -
                        PLC: 1
                        <hr />
                        <div id="Habilitacion">
                            <b>
                                <label class="label">Habilitación</label>
                            </b>
                            <div id="botonesHabilitacion">
                                <button type="button" class="btn btn-success" id="btnHabilitar:" onclick="EjecutarComando('@Model.ID_SECTOR',1,'S_LECTURA_RFID.Estado')">
                                    Habilitar
                                </button>
                                <button type="button" class="btn btn-danger" id="btnDeshabilitar:" onclick="EjecutarComando('@Model.ID_SECTOR',0,'S_LECTURA_RFID.Estado')">
                                    Deshabilitar
                                </button>
                            </div>
                        </div>
                        <hr />
                        <div id="TiempoRetardo" class="text-center">
                            <label class="label">Tiempo de retardo: </label>
                            <input type="number" class="input-sm text-center" id="TiempoRetardoSENSOR" />
                            <br />
                            <button class="btn btn-dark text-center" id="btnCambioTiempoRetardoSENSOR">Aceptar</button>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cerrarModal()">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-primary" id="btnSENSOR" data-toggle="modal" data-target="#ModalSENSOR">
            SENSOR
        </button>
    </div>
}
@if (ViewBag.estadoBarrera != "NULL")
{
    <div class="column">

        <!-- Modal content-->
        <div class="modal" id="modalBARRERA" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header" id="DescripcionBarrera1">
                        <b>
                            BARRERA
                        </b>
                    </div>
                    <div class="modal-body text-center">
                        <div id="EstadoBarrera1">
                            @*     @Html.Action("Barrera", "ControlesAcceso", new { tag = "BARRERA1", idSector = 10 })*@
                        </div>
                        Sector: @Model.ID_SECTOR
                        -
                        PLC: 0
                        <hr />
                        <div id="ComandosBarrera1">
                            <b>
                                Comandos
                            </b>
                            <br />
                            <br />
                            <div id="btnComandoBarrera1">
                                <div id="btnAutDes">
                                    <button type="button" class="btn btn-success" id="btnAutomatico:" onclick="EjecutarComando('@Model.ID_SECTOR',2,'BARRERA.Comando')">
                                        Automático
                                    </button>
                                    <button type="button" class="btn btn-danger" id="btnDeshabilitar:" onclick="EjecutarComando('@Model.ID_SECTOR',1,'BARRERA.Comando')">
                                        Deshabilitar
                                    </button>
                                </div>
                                <br />
                                <div id="btnSubirBajar1">
                                    <button type="button" class="btn btn-outline-dark" id="btnSubirBarrera:" onclick="EjecutarComando('@Model.ID_SECTOR',3,'BARRERA.Comando')">
                                        <i class="fa fa-fw fa-arrow-up"></i>
                                    </button>
                                    <button type="button" class="btn btn-outline-dark" id="btnBajarBarrera:" onclick="EjecutarComando('@Model.ID_SECTOR',4,'BARRERA.Comando')">
                                        <i class="fa fa-fw fa-arrow-down"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cerrarModal()">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

        <button class="btn btn-primary" id="btnBARRERA" data-toggle="modal" data-target="#modalBARRERA">
            BARRERA
        </button>
    </div>
}
<div class="column">




    <div class="modal" id="modalAyudaSensBarr" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header" id="DescripcionBarrera">
                    <b>
                        Ayuda
                    </b>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <div class="text-center">
                                    Sensores
                                </div>
                                <div class="font-weight-normal">
                                    <div>
                                        <button type="button" class="btn">SENSOR</button> Deshab.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-danger">SENSOR</button> Con presencia.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-success">SENSOR</button> Sin presencia.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-warning">SENSOR</button> Falla.
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm">
                                <div class="text-center">
                                    Barreras
                                </div>
                                <div class="font-weight-normal">
                                    <div>
                                        <button type="button" class="btn">BARRERA</button> Deshab.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-primary">BARRERA</button> Autom.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-success">BARRERA</button> Manual.
                                    </div>
                                    <br />
                                    <div>
                                        <button type="button" class="btn btn-warning">BARRERA</button> Falla.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cerrarModal()">Cerrar</button>
                </div>

            </div>
        </div>
    </div>

    <button class="btn btn-primary" id="btnAyudaSenBarr" data-toggle="modal" data-target="#modalAyudaSensBarr">
        <i class="fa fa-fw fa-question"></i>
    </button>

</div>

AxControlWeb/Views/Sectores/_DinamismoBalanza.cshtml
@model Entidades.SECTOR

<div id="@Model.ID_SECTOR">
    <h5>@Model.DESCRIPCION</h5>
</div>

<div class="table-responsive" style="display:block;overflow-x:auto;white-space:nowrap;">
    <table class="table">
        <tbody>
            <tr>
                <td>
                    <img src="~/Content/img/Controles/Espira/@(ViewBag.EstadoS_Lect).png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Barrera/@(ViewBag.EstadoBar1).png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Sensor/@(ViewBag.EstadoS1_Bar).png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Sensor/@(ViewBag.EstadoS1_Pos).png" class="h-50 d-inline-block" />
                </td>
                <td style="vertical-align: bottom;display: table-cell;">
                    <img src="~/Content/img/Controles/Balanza/Balanza.png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Sensor/@(ViewBag.EstadoS2_Pos).png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Barrera/@(ViewBag.EstadoBar2).png" class="h-50 d-inline-block" />
                </td>
                <td>
                    <img src="~/Content/img/Controles/Sensor/@(ViewBag.EstadoS2_Bar).png" class="h-50 d-inline-block" />
                </td>
            </tr>
        </tbody>
    </table>
</div>
<br />
<script>

</script>

AxControlWeb/Views/Sectores/_sector.cshtml
@model Entidades.SECTOR



    @{
        if (Model.ID_SECTOR >= 100 && Model.ID_SECTOR < 200)
        {
            @Html.Action("DinamismoPorteria_", "ControlAcceso", new { idControl = Model.ID_CONTROL_ACCESO })
            
        }
        else if (Model.ID_SECTOR >= 200 && Model.ID_SECTOR < 300)
        {

        }
        else if (Model.ID_SECTOR >= 400 && Model.ID_SECTOR < 500)
        {
            switch (Model.ID_SECTOR)
            {
                case 410:
                case 420:
                case 440:
                case 450:
                    @Html.Action("_DinamismoBalanza", "Sectores", new { idSector = Model.ID_SECTOR })
                    //Html.Action("_DinamismoBalanza", "Sectores", new { idSector = Model.ID_SECTOR });
                    break;
            }

        }
        else if (Model.ID_SECTOR >= 500 && Model.ID_SECTOR < 600)
        {

        }
        @*else if (Model.ID_SECTOR >= 600 && Model.ID_SECTOR < 700)
        {

        }
        else if (Model.ID_SECTOR >= 700 && Model.ID_SECTOR < 800)
        {
            @Html.Action("_DinamismoPorteria", "Sectores", new { idSector = Model.ID_SECTOR })
        }
        else if (Model.ID_SECTOR >= 800 && Model.ID_SECTOR < 900)
        {
            @Html.Action("_DinamismoPorteria", "Sectores", new { idSector = Model.ID_SECTOR })
        }
        else if (Model.ID_SECTOR >= 900 && Model.ID_SECTOR < 1000)
        {

        }
        else if (Model.ID_SECTOR >= 1200 && Model.ID_SECTOR < 1300)
        {
            @Html.Action("_DinamismoPorteria", "Sectores", new { idSector = Model.ID_SECTOR })
        }*@




    }